[package]
name = "zoisite-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
zoisite = { path = "../compiler" }
tower-lsp = "0.20.0"
tokio = { version = "1.41.0", features = ["full"] }
text-size = "1.1.1"
dashmap = "6.1.0"
ropey = "1.6.1"
